name: Spring Boot & Gradle CI Jobs (With. main branches push)

on:
  push:
    branches: [ chore(#27)-github-action ]

jobs:
  build:
    # 실행 환경 (Git Runners 개인 서버)
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    # application.yml 파일 설정

    # gradlew를 실행시키기 위해 권한 부여
    - name: Gradlew에게 실행권한 부여
      run: chmod +x gradlew

    # 멀티모듈 빌드하기
    - name: 멀티모듈 전체 빌드
      run: ./gradlew build
    
    
